## [Ломать — не строить 2](../../../solutions/5.3/53_c.py)

Вашему решению будет предоставлена функция `func`, которая на этот раз принимает неограниченное число позиционных параметров и производит с ними некую операцию __приведения типа__.

Предложите вызов функции, который гарантированно породит ошибку внутри функции.

### Примечание

Если ошибка произойдёт внутри функции, то она будет перехвачена и обработана.\
Если же она произойдет в вашем коде, то программа будет завершена с ошибкой.

### Пример 1

__Ввод__
```python
def func(a, b, c):
    return ''.join(map(str, (a, b, c)))
```

__Вывод__
```plaintext
Ура! Ошибка!
```

### Пример 2

__Ввод__
```python
def func(a, b):
    return set(a) ^ set(b)
```

__Вывод__
```plaintext
Ура! Ошибка!
```