## [Валидация имени пользователя](../../../solutions/5.3/53_h.py)

Продолжим реализацию системы валидации.

Напишите функцию `username_validation`, которая принимает один позиционный аргумент — имя пользователя:

Если параметр не является строкой, то вызовите исключение `TypeError`.

А также разработайте собственные ошибки:

- `BadCharacterError` — вызывается, если значение состоит не только из латинских букв, цифр и символа нижнего подчёркивания;
- `StartsWithDigitError` — вызывается, если значение начинается с цифры.

Обработка ошибок должна происходить в порядке, указанном в задании.

В случае успешного выполнения, функция должна вернуть переданный параметр без изменений.

### Примечание

В решении не должно быть вызовов требуемых функций.

### Пример 1

__Ввод__
```python
print(username_validation("$user_45$"))
```

__Вывод__
```plaintext
Вызвано исключение BadCharacterError
```

### Пример 2

__Ввод__
```python
print(username_validation("45_user"))
```

__Вывод__
```plaintext
Вызвано исключение StartsWithDigitError
```