## [Валидация пользователя](../../../solutions/5.3/53_i.py)

Используйте две предыдущих функции валидации и напишите функцию `user_validation`, которая принимает именованныеаргументы:

- `last_name` — фамилия;
- `first_name` — имя;
- `username` — имя пользователя.

Если функции был передан неизвестный параметр или не передан один из обязательных, то вызовите исключение `KeyError`.

Если один из параметров не является строкой, то вызовите исключение `TypeError`.

Обработка данных должна происходить в порядке: фамилия, имя, имя пользователя.

Если поле заполнено верно, функция возвращает словарь с данными пользователя.

### Примечание

В решении не должно быть вызовов требуемых функций.

### Пример 1

__Ввод__
```python
print(user_validation(last_name="Иванов", first_name="Иван", username="ivanych45"))
```

__Вывод__
```plaintext
{'last_name': 'Иванов', 'first_name': 'Иван', 'username': 'ivanych45'}
```

### Пример 2

__Ввод__
```python
print(user_validation(last_name="Иванов", first_name="Иван", username="ivanych45", password="123456"))
```

__Вывод__
```plaintext
Вызвано исключение KeyError
```